(define-library (bc defstruct)
 (import (chibi) (only (meta) warn) (scheme cxr))
 (import (srfi 1))
 (import (srfi 17))
 (import (srfi 9))
 (import (bc chicken-misc))
 (import (bc format))
 (include "defstruct.scm")
 (export defstruct))
