(define-library (bc defstruct)
 (import (meta))
 (import (chibi))
 (import (scheme base))
 (import (scheme cxr))
 (import (srfi 1))
 (import (srfi 17))
 (import (bc chicken-misc))
 (import (format))
 (include "defstruct.scm")
 (export defstruct))
