(define-library (bc obj)
  (import (chibi)
          (bc defstruct) (bc format) (bc chicken-misc)
          (srfi 1) (srfi 17) (srfi 39) (srfi 69)
          (chibi ast)
          (only (scheme base) call/cc when unless let-values)
          (scheme cxr))
  (include "obj-methods-internal.scm")
  (include "obj-methods-syntax.scm")
  (include "obj-classes.scm")
  (include "obj-default-classes.scm")
)
