(define-library (bcaine defstruct)
 (import (chibi) (only (meta) warn) (scheme cxr))
 (import (srfi 1))
 (import (srfi 17))
 (import (srfi 9))
 (import (bcaine misc-util))
 (import (bcaine format))
 (include "defstruct.scm")
 (export defstruct))
