(define-library (bcaine obj-test)
  (import (chibi)
          (bcaine defstruct) (bcaine format) (bcaine misc-util)
          (srfi 1) (srfi 2) (srfi 17) (srfi 39) (srfi 69)
          (chibi ast)
          (chibi test)
          (only (scheme base) call/cc when unless let-values)
          (scheme cxr))
  (include "obj-methods-internal.scm")
  (include "obj-methods-syntax.scm")
  (include "obj-classes.scm")
  (include "obj-default-classes.scm")
  (include "obj-test.scm")
  (export main))
